---
abstract: 'a thenable Future like Q module for JavaScript'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Carp: 0
  FindBin: 0
  Scalar::Util: 0
  Test::Identity: 0
  Test::Memory::Cycle: 0
  Test::MockModule: 0.05
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Future-Q
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
provides:
  Future::Q:
    file: lib/Future/Q.pm
    version: 0.030
requires:
  Carp: 0
  Devel::GlobalDestruction: 0
  Future: 0.13
  Scalar::Util: 0
  Try::Tiny: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.030
